markdown:         rdiscount
pygments:         true
paginate:         6
permalink: 		  none
exclude: _posts/2014-06-11-告白.textile

title:            未来某天
url:              http://xushao1990.github.com
feed:             /atom.xml
author:
    name:         未来某天
    email:        xushao1990@126.com
description:      "some day in future"

about: 			  "2012年毕业山理工，从事iOS开发1年半。磕磕绊绊，时常感到自身的浅陋。生活工作总会有惊喜，有些小念头，便这里记下来。"
man: 			  "不积跬步无以至千里 不积小流无以成江海"

follow:
    github:       https://github.com/xushao1990
description:      "未来某天的博客"


style: 			  /css/style.css
blogName: 		  未来某天
blogDesc: 		  some day in future
